# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

def shared_pods
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SinhVienUIT
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'react-native-calendar-events', :path =>'../node_modules/react-native-calendar-events'
  pod 'react-native-cookies', :path =>'../node_modules/react-native-cookies/ios'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'ART',
    'Core',
    'BatchedBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

end

target 'SinhVienUIT' do
  shared_pods
end

target 'SinhVienUITTests' do
  shared_pods
end
